name: Nieuwe feature
description: Ik heb een idee voor een nieuwe feature of verbetering
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Bedankt voor het aandragen van een nieuwe feature. Beschrijf zo duidelijk mogelijk je idee of verbetering.
        Voordat je aan de slag gaat met dit formulier, nog een puntje:
        - Heeft iemand anders al eens een soortgelijk issue ingediend? Check dit in de [backlog](https://github.com/developer-overheid-nl/don-tools-api/issues).
  - type: textarea
    id: description
    attributes:
      label: Omschrijving
      description: Beschrijf de feature of verbetering, heb je een link naar een voorbeeld of andere informatie voeg deze ook toe.
    validations:
      required: true
  - type: textarea
    id: remarks
    attributes:
      label: Opmerkingen
      description: Heb je nog andere opmerkingen of iets wat je wilt delen met ons, laat dat hier achter.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Alvast bedankt voor je bijdrage.

        Het team van Developer Overheid NL
